### ISSUE TITLE
Amendment-detail fix change recommendation

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2946]
**Current behaviour:**
In Amendment-detail view (you need an amendment which changes more than one line)
- [x] A. If a change recommendation is added then the original version of the motion is displayed, not the Diff Version anymore. 
- [x] B. If the change recommendation is deleted then you need to reload the page to see the change recommendation anymore
- [x] B.1. If a change recommendation is added, the whole motion text can't be activated with the checkbox "Show entire motion text". By clicking it an error appears in the console. Error message "Cannot read properties of null (reading 'offsetTop')" 
- [x] C. If an amendment changes several lines and has one change request then the line numbers are not correctly displayed
- [x] D. If an amendment has a change recommendation then the option "show entire motion text" vanishes

Descriptions changed because Case C and D are resolved and A/B needed a rework.

**Reproduction:**
In a meeting:
1. create a motion with several lines/paragraphs (I recommend 7 lines)
2. create an amendment which changes several (but not all) lines in the motion
3. add a change recommendation to the amendment
    3.1. hover around the beginning of the sentence (a bit more to the left) until you find a blue cross-icon
    3.2. press the icon
    3.3. change something in the sentence and save (hint: doesn't matter, if it is a part of the change recommendation or the regular text.)
4. ( **Case A)** ) now the original version of the amendment is active, not the Diff Version (compare: in a motion the Diff Version is active after adding a change recommendation.)
5. **(Case B)** Original version must be active.-  Open the console. Now activate the checkbox "Show entire motion text". An Error message appears in the console. The entire motion is not displayed. -> Reload the page to switch back to a working version.
6. **(Case B.1)** Delete the change recommendation. -> CR stays active and visible. By deleting it twice, a correct error message appears.
7. reload the page -> the change recommedantion is gone

**Wanted behaviour:**
- [x] A. - After adding a change recommendation to an amendment, the Diff Version should be visible. It should follow the same logic like adding an amendment to a motion. Please check, if this is connected to the function "Default text version for change recommendations and projections of motions".
- [ ] B. - the change recommendation should vanish after deletion without reload
- [x] B.1 - activated checkbox "Show entire motion text" should show whole motion text
- [x] the displayed lines should be correct even if there is a change request
- [x] the optiojjn to display the whole text should always be available

**Comment by Elblinator** [comment]
Case D) only happens if the Diff Version is selected. @emanuelschuetze @MSoeb is this a feature?

If it is, ignore D)

**Comment by Elblinator** [comment]
Case C is solved #2970

**Comment by Elblinator** [comment]
Case D) is wanted behaviour

**Comment by MSoeb** [comment]
Re-Tested and rewrited the issue:
- Case A: Edit to reflect the occuring problem
- Case B: Still occurs. Also found another problem which is strongly connected to it. Integrated it in the issue in B.1

**Comment by reiterl** [comment]
I looked into Case A: I can reproduce a failure there. In the `os-motion-highlight-form` the function `determineCrMode`
doesn't work in this case. It sets the cr mode to original in a if clause, which shouldn't happen. The `hasChangeRecommendation` property returns a false, but it should return a true.  I need more time to debug this.

**Comment by reiterl** [comment]
Add some fixes. I debugged here a lot, but there are still some issues here. I stop working on this.
Case A and part of B1 should be fixed.

**Comment by MSoeb** [comment]
Re-Test:
Case A) still occurs
Case B) CR deletion -> still occurs
Case B.1) can't reproduce it. seems to work correctly

**Comment by bastianjoel** [comment]
Very likely to be resolved after #4023 is finished.
